#!/usr/bin/env python3
# =============================================================================
# ml/spark_mllib_model.py
# Spark MLlib Distributed Random Forest — Large-Scale Prediction on the Full Dataset
# =============================================================================
# This module trains a distributed Random Forest model on the entire EDGAR dataset 
# using Spark MLlib.
#
# WHY SPARK MLLIB?
#   - EDGAR dataset is large: 20 countries × 7 sectors × 34 years = 4760+ records
#   - All data is partitioned across workers using Spark's distributed memory
#   - Enables model training at a scale impossible on a single machine
#   - Pipeline API: preprocessing + model in a single unified chain
#
# SPARK ML PIPELINE:
#   Raw CSV → StringIndexer → VectorAssembler → Random Forest → Prediction
#
# Usage:
#   python ml/spark_mllib_model.py
# =============================================================================

import os
import json
import logging
from pathlib import Path

from pyspark.sql import SparkSession
from pyspark.sql import functions as F
from pyspark.sql.types import *

# Spark MLlib components
from pyspark.ml import Pipeline                       # ML Pipeline chain
from pyspark.ml.feature import (
    StringIndexer,    # Categorik → numerical conversion
    VectorAssembler,  # Assemble feature columns into a single vector
    StandardScaler,   # Normalize features
    OneHotEncoder     # Categorical encoding (alternative)
)
from pyspark.ml.classification import RandomForestClassifier  # For classification
from pyspark.ml.regression import (
    RandomForestRegressor,    # For regression
    GBTRegressor              # Gradient Boosted Trees (Spark version)
)
from pyspark.ml.evaluation import (
    RegressionEvaluator,
    MulticlassClassificationEvaluator
)
from pyspark.ml.tuning import (
    CrossValidator,    # K-fold cross-validation
    ParamGridBuilder   # Hyperparameter grid
)

logging.basicConfig(level=logging.INFO, format='%(asctime)s [%(levelname)s] %(message)s')
logger = logging.getLogger('spark_mllib')

BASE_DIR   = Path(__file__).parent.parent
DATA_DIR   = BASE_DIR / "data"
MODELS_DIR = BASE_DIR / "ml" / "saved_models"
MONGO_URI  = os.getenv("MONGO_URI", "mongodb://admin:password@localhost:27017/carbon_footprint")
MODELS_DIR.mkdir(parents=True, exist_ok=True)


def create_spark_session() -> SparkSession:
    """
    Creates a Spark Session for MLlib training.
    
    When running in cluster mode (docker-compose):
    - spark-master:7077 is used
    - Workers automatically receive tasks
    - Spark UI: http://localhost:8080 (master UI)
    """
    spark = (SparkSession.builder
        .appName("CarbonFootprint-MLlib-RandomForest")
        .master(os.getenv("SPARK_MASTER", "local[*]"))
        .config("spark.jars.packages",
                "org.mongodb.spark:mongo-spark-connector_2.12:10.3.0")
        .config("spark.mongodb.write.connection.uri", MONGO_URI)
        .config("spark.driver.memory", "4g")
        .config("spark.executor.memory", "2g")
        .config("spark.sql.shuffle.partitions", "16")
        .config("spark.sql.adaptive.enabled", "true")
        .getOrCreate()
    )
    spark.sparkContext.setLogLevel("WARN")
    logger.info(f"✓ MLlib Spark Session | Master: {spark.sparkContext.master}")
    return spark


def load_edgar_data(spark: SparkSession):
    """
    Loads the EDGAR Dataset into a Spark DataFrame.
    
    This function attempts to load data from both Parquet (fast) and CSV.
    Parquet is preferred because:
    - Columnar storage → only required columns are read
    - Compression → less I/O
    - Schema embedded → no type casting required
    """
    # Try Parquet first (generated by batch loader)
    parquet_path = DATA_DIR / "edgar" / "parquet"
    if parquet_path.exists():
        logger.info(f"Loading from Parquet: {parquet_path}")
        df = spark.read.parquet(str(parquet_path))
    else:
        # Load CSV
        csv_path = DATA_DIR / "edgar" / "edgar_country_sector_1990_2023.csv"
        if not csv_path.exists():
            logger.error(f"EDGAR data not found: {csv_path}")
            return None
        
        logger.info(f"Loading from CSV: {csv_path}")
        df = (spark.read
              .option("header", "true")
              .option("inferSchema", "true")
              .csv(str(csv_path))
        )
    
    count = df.count()
    logger.info(f"Number of loaded EDGAR records: {count:,}")
    logger.info(f"Schema:")
    df.printSchema()
    
    return df


def build_regression_pipeline(feature_cols: list, label_col: str):
    """
    Creates a Spark ML Pipeline — Regression (Random Forest)
    
    Pipeline steps:
    1. StringIndexer: country, sector → numerical indices
    2. VectorAssembler: assemble all features into a single vector
    3. StandardScaler: normalize the vector
    4. RandomForestRegressor: model training
    
    Pipeline advantage:
    - Preprocessing and model are managed as a single unit
    - No data leakage during cross-validation
    - transform() call applies all steps sequentially
    
    Args:
        feature_cols: Feature columns to use
        label_col: Target variable column name
    
    Returns:
        Spark ML Pipeline
    """
    stages = []
    
    # Convert categorical columns to numerical indices
    # StringIndexer: most frequent value = 0, second = 1, ...
    categorical_features = []
    for col in ['country_code', 'country', 'sector']:
        if col in feature_cols:
            indexer = StringIndexer(
                inputCol=col,
                outputCol=f"{col}_idx",
                handleInvalid="keep"   # Unseen categories → last index
            )
            stages.append(indexer)
            categorical_features.append(f"{col}_idx")
    
    # Numerical features (used directly)
    numeric_features = [c for c in feature_cols
                        if c not in ['country_code', 'country', 'sector']]
    
    all_features = numeric_features + categorical_features
    
    # VectorAssembler: assemble all features into a DenseVector
    # MLlib models expect a single 'features' vector
    assembler = VectorAssembler(
        inputCols=all_features,
        outputCol="raw_features",
        handleInvalid="keep"   # Process NaN values as zero
    )
    stages.append(assembler)
    
    # StandardScaler: normalize features (mean=0, std=1)
    scaler = StandardScaler(
        inputCol="raw_features",
        outputCol="features",
        withMean=True,   # Center the data
        withStd=True     # Scale by standard deviation
    )
    stages.append(scaler)
    
    # Random Forest Regressor
    # numTrees: more trees = better but slower
    # maxDepth: deep trees overfit
    rf_regressor = RandomForestRegressor(
        featuresCol="features",
        labelCol=label_col,
        numTrees=100,          # 100 decision trees — ensemble power
        maxDepth=8,            # Maximum tree depth
        minInstancesPerNode=5, # Minimum instances per node
        featureSubsetStrategy="auto",  # Auto feature subset strategy
        seed=42
    )
    stages.append(rf_regressor)
    
    pipeline = Pipeline(stages=stages)
    return pipeline


def train_distributed_random_forest(spark: SparkSession) -> dict:
    """
    Distributed Random Forest Training on the entire EDGAR Dataset
    
    This function represents the 'Batch Layer' model training of the Lambda architecture.
    Utilizes Spark's distributed computing for large data sizes.
    
    Cross-Validation: hyperparameter selection via 3-fold CV
    (5-fold is recommended in production, but 3-fold is faster for demo)
    
    Args:
        spark: Active SparkSession
    
    Returns:
        Trained model and metrics
    """
    logger.info("\n" + "="*60)
    logger.info("Spark MLlib — Distributed Random Forest Training")
    logger.info("="*60)
    
    # Load EDGAR data
    df = load_edgar_data(spark)
    if df is None:
        return {}
    
    # === FEATURE ENGINEERING (with Spark SQL) ===
    df_features = (df
        # Drop null values
        .dropna(subset=["emission_mtco2"])
        .filter(F.col("emission_mtco2") > 0)
        # Year-based features
        .withColumn("decade",          (F.col("year") / 10).cast("int") * 10)
        .withColumn("years_from_1990", F.col("year") - 1990)
        # Log transform: emission values are right-skewed
        # Log transform addresses this, improving model performance
        .withColumn("log_emission",    F.log1p("emission_mtco2"))
    )
    
    # Target variable
    label_col = "emission_mtco2"
    
    # Feature columns
    feature_cols = [
        "year", "decade", "years_from_1990",
        "per_capita_tco2",
        "country_code", "sector"   # These will be encoded using StringIndexer
    ]
    
    # Filter to available columns
    available = [c for c in feature_cols if c in df_features.columns]
    logger.info(f"Used features: {available}")
    
    # Train/test split
    # randomSplit: Spark's distributed splitting function
    train_df, test_df = df_features.randomSplit([0.80, 0.20], seed=42)
    
    train_count = train_df.count()
    test_count  = test_df.count()
    logger.info(f"Train: {train_count:,} | Test: {test_count:,}")
    
    # Build pipeline
    pipeline = build_regression_pipeline(available, label_col)
    
    # === CROSS VALIDATION (Hyperparameter Selection) ===
    # ParamGridBuilder: hyperparameter combinations to test
    param_grid = (ParamGridBuilder()
        # Stage 3 = RF Regressor (0-indexed: StringIndexers + Assembler + Scaler + RF)
        .addGrid(pipeline.getStages()[-1].numTrees, [50, 100])   # 2 choices
        .addGrid(pipeline.getStages()[-1].maxDepth, [5, 8])      # 2 choices
        .build()
    )
    # Total 4 combinations × 3-fold = 12 models trained
    
    evaluator = RegressionEvaluator(
        labelCol=label_col,
        predictionCol="prediction",
        metricName="rmse"           # Select the best model using RMSE
    )
    
    logger.info(f"Starting cross-validation: {len(param_grid)} combinations × 3-fold...")
    
    cv = CrossValidator(
        estimator=pipeline,
        estimatorParamMaps=param_grid,
        evaluator=evaluator,
        numFolds=3,           # 3-fold CV (sufficient for demo)
        seed=42
    )
    
    # Train — this process may take a few minutes (Spark runs distributed)
    cv_model = cv.fit(train_df)
    
    logger.info("✓ Cross-validation completed")
    logger.info(f"CV metrics: {[round(m, 4) for m in cv_model.avgMetrics]}")
    
    # Best model
    best_model = cv_model.bestModel
    
    # Test set evaluation
    test_predictions = best_model.transform(test_df)
    
    rmse = evaluator.evaluate(test_predictions)
    
    mae_evaluator = RegressionEvaluator(
        labelCol=label_col, predictionCol="prediction", metricName="mae"
    )
    mae = mae_evaluator.evaluate(test_predictions)
    
    r2_evaluator = RegressionEvaluator(
        labelCol=label_col, predictionCol="prediction", metricName="r2"
    )
    r2 = r2_evaluator.evaluate(test_predictions)
    
    logger.info(f"\nRandom Forest Test Results:")
    logger.info(f"  MAE:  {mae:.4f} MtCO2")
    logger.info(f"  RMSE: {rmse:.4f} MtCO2")
    logger.info(f"  R²:   {r2:.4f}")
    
    # Write predictions to MongoDB
    logger.info("Writing predictions to MongoDB...")
    (test_predictions
        .select("country_code", "sector", "year", label_col, "prediction")
        .withColumn("model_type", F.lit("SparkMLlib_RandomForest"))
        .withColumn("prediction_date", F.current_timestamp())
        .write
        .format("mongodb")
        .mode("append")
        .option("database",   "carbon_footprint")
        .option("collection", "ml_predictions")
        .save()
    )
    
    # Feature importance (Random Forest's built-in feature importance)
    rf_stage = best_model.stages[-1]
    logger.info(f"\nModel features:")
    logger.info(f"  Number of trees: {rf_stage.getNumTrees}")
    logger.info(f"  Feature importance: {rf_stage.featureImportances}")
    
    # Save the model
    model_save_path = str(MODELS_DIR / "spark_rf_model")
    best_model.save(model_save_path)
    logger.info(f"✓ Model saved: {model_save_path}")
    
    metrics = {
        "model_type": "SparkMLlib_RandomForest",
        "mae":        float(mae),
        "rmse":       float(rmse),
        "r2":         float(r2),
        "train_size": train_count,
        "test_size":  test_count,
        "best_params": str(cv_model.getEstimatorParamMaps()[cv_model.avgMetrics.index(min(cv_model.avgMetrics))])
    }
    
    # Save metrics to a JSON file as well
    metrics_path = MODELS_DIR / "spark_rf_metrics.json"
    with open(metrics_path, 'w') as f:
        json.dump(metrics, f, indent=2)
    
    return {"model": best_model, "metrics": metrics}


def main():
    """
    Main function — distributed Random Forest training.
    """
    logger.info("Starting Spark MLlib Model...")
    
    spark = create_spark_session()
    
    try:
        results = train_distributed_random_forest(spark)
        
        if results:
            logger.info("\n✓ Distributed Random Forest training completed!")
            logger.info(f"Final metrics:")
            for k, v in results['metrics'].items():
                logger.info(f"  {k}: {v}")
    except Exception as e:
        logger.error(f"MLlib training error: {e}", exc_info=True)
        raise
    finally:
        spark.stop()
        logger.info("Spark Session closed")


if __name__ == "__main__":
    main()
