#!/usr/bin/env python3
# =============================================================================
# ml/train_all.py
# Master Training Orchestrator — Trains All Models Sequentially
# =============================================================================
# This script trains all ML models sequentially and logs the results:
#   1. XGBoost Regression (CO2 prediction)
#   2. XGBoost Classification (individual footprint)
#   3. LSTM (time-series forecasting)
#   4. Spark MLlib Random Forest (distributed)
#
# MLFLOW Integration:
#   - An experiment is logged for each model run
#   - Metrics, parameters, and artifacts are saved
#   - MLflow UI: http://localhost:5000 (opened via mlflow ui command)
#
# Usage:
#   python ml/train_all.py
#   python ml/train_all.py --skip-spark   # Skip Spark MLlib (fast testing)
#   python ml/train_all.py --skip-lstm    # Skip LSTM (if GPU is not needed)
# =============================================================================

import os
# Configure threading limits to prevent OpenMP duplicate/initialization segfaults on macOS
os.environ["OMP_NUM_THREADS"] = "1"
os.environ["MKL_NUM_THREADS"] = "1"
os.environ["OPENBLAS_NUM_THREADS"] = "1"
os.environ["VECLIB_MAXIMUM_THREADS"] = "1"
os.environ["NUMEXPR_NUM_THREADS"] = "1"

import sys
from pathlib import Path
sys.path.append(str(Path(__file__).parent.parent))
import json
import time
import logging
import argparse
from pathlib import Path
from datetime import datetime

import numpy as np
import pandas as pd
import mlflow
import mlflow.xgboost
import mlflow.pytorch
import mlflow.sklearn

# Force root logger level and configure handlers to bypass library overrides
root_logger = logging.getLogger()
root_logger.setLevel(logging.INFO)
# Clear any existing handlers to prevent duplicates or silent logs
for h in list(root_logger.handlers):
    root_logger.removeHandler(h)
handler = logging.StreamHandler(sys.stdout)
handler.setLevel(logging.INFO)
handler.setFormatter(logging.Formatter('%(asctime)s [%(levelname)s] %(message)s'))
root_logger.addHandler(handler)

logger = logging.getLogger('train_all')
logger.setLevel(logging.INFO)


BASE_DIR   = Path(__file__).parent.parent
DATA_DIR   = BASE_DIR / "data"
MODELS_DIR = BASE_DIR / "ml" / "saved_models"
MODELS_DIR.mkdir(parents=True, exist_ok=True)

# MLflow experiment settings
MLFLOW_EXPERIMENT = "CarbonFootprint_Prediction"
MLFLOW_TRACKING   = str(BASE_DIR / "mlruns")  # Local MLflow directory


def setup_mlflow():
    """
    Initializes MLflow experiment tracking.
    
    What MLflow records:
    - Metrics: MAE, RMSE, R², Accuracy, F1
    - Parameters: learning rate, tree count, epoch count
    - Artifacts: trained model files
    - Timestamps and duration
    
    To open the UI:
        mlflow ui --backend-store-uri ./mlruns
        → http://localhost:5000
    """
    mlflow.set_tracking_uri(f"file://{MLFLOW_TRACKING}")
    
    # Create experiment if it doesn't exist
    experiment = mlflow.get_experiment_by_name(MLFLOW_EXPERIMENT)
    if experiment is None:
        mlflow.create_experiment(MLFLOW_EXPERIMENT)
    
    mlflow.set_experiment(MLFLOW_EXPERIMENT)
    logger.info(f"✓ MLflow tracking: {MLFLOW_TRACKING}")
    logger.info(f"  Experiment: {MLFLOW_EXPERIMENT}")


def load_carbon_monitor_data() -> pd.DataFrame:
    """
    Loads Carbon Monitor processed data.
    Uses either the Parquet generated by the batch pipeline or raw CSV.
    
    Returns:
        Feature engineered DataFrame
    """
    # Try Parquet first
    parquet_path = DATA_DIR / "carbon_monitor" / "processed_parquet"
    csv_path     = DATA_DIR / "carbon_monitor" / "carbon_monitor_global.csv"
    
    if parquet_path.exists():
        logger.info("Loading Carbon Monitor data from Parquet...")
        df = pd.read_parquet(str(parquet_path))
    elif csv_path.exists():
        logger.info("Loading Carbon Monitor data from CSV...")
        df = pd.read_csv(csv_path)
        
        # If batch pipeline is not run, perform feature engineering
        if 'lag_1d' not in df.columns:
            logger.info("Applying feature engineering...")
            df = apply_feature_engineering(df)
    else:
        logger.warning("Carbon Monitor data not found, generating synthetic data...")
        df = generate_quick_synthetic_data()
    
    logger.info(f"Loaded: {len(df):,} records, {len(df.columns)} columns")
    return df


def apply_feature_engineering(df: pd.DataFrame) -> pd.DataFrame:
    """
    Applies quick feature engineering on raw CSV.
    Used if batch pipeline has not been executed.
    
    Args:
        df: Raw Carbon Monitor DataFrame
    
    Returns:
        Feature engineered DataFrame
    """
    # Find date column
    date_col = next((c for c in df.columns if 'date' in c.lower()), None)
    if date_col:
        df['emission_date'] = pd.to_datetime(df[date_col])
    
    # Normalize emission column
    emission_col = next(
        (c for c in df.columns if 'MtCO2' in c or 'mtco2' in c.lower() or 'emission' in c.lower()),
        df.columns[-1]
    )
    df = df.rename(columns={emission_col: 'mtco2_per_day'})
    
    # Time features
    df['year']        = df['emission_date'].dt.year
    df['month']       = df['emission_date'].dt.month
    df['day_of_week'] = df['emission_date'].dt.dayofweek
    df['day_of_year'] = df['emission_date'].dt.dayofyear
    df['quarter']     = df['emission_date'].dt.quarter
    df['is_weekend']  = (df['day_of_week'] >= 5).astype(int)
    df['month_sin']   = np.sin(2 * np.pi * df['month'] / 12)
    df['month_cos']   = np.cos(2 * np.pi * df['month'] / 12)
    
    # Lag and rolling averages (for each country-sector group)
    df = df.sort_values(['country', 'sector', 'emission_date'])
    
    group_cols = ['country', 'sector']
    
    for grp_cols in [group_cols]:
        g = df.groupby(grp_cols)['mtco2_per_day']
        df['lag_1d']         = g.shift(1)
        df['lag_7d']         = g.shift(7)
        df['lag_30d']        = g.shift(30)
        df['rolling_avg_7d'] = g.transform(lambda x: x.rolling(7,  min_periods=1).mean())
        df['rolling_avg_30d']= g.transform(lambda x: x.rolling(30, min_periods=1).mean())
    
    # 'date' alias
    if 'date' not in df.columns and date_col:
        df['date'] = df['emission_date'].dt.strftime('%Y-%m-%d')
    
    return df.dropna(subset=['lag_7d'])


def generate_quick_synthetic_data(n_per_group: int = 500) -> pd.DataFrame:
    """
    Generates quick synthetic data (if data is missing).
    Used to verify whether models function properly.
    
    Args:
        n_per_group: Samples per country-sector group
    
    Returns:
        Realistic synthetic DataFrame
    """
    logger.info("Generating synthetic training data...")
    np.random.seed(42)
    
    countries = ['CN', 'US', 'IN', 'DE', 'TR']
    sectors   = ['Power', 'Ground Transport', 'Industry']
    base_emissions = {'CN': 2.5, 'US': 1.8, 'IN': 0.8, 'DE': 0.15, 'TR': 0.09}
    
    all_records = []
    
    for country in countries:
        for sector in sectors:
            base = base_emissions[country] * np.random.uniform(0.3, 1.0)
            dates = pd.date_range('2020-01-01', periods=n_per_group, freq='D')
            
            # Realistic emission series: trend + seasonality + noise
            t = np.arange(n_per_group)
            trend    = base * (1 + 0.001 * t)                                # Rising trend
            seasonal = 0.1 * base * np.sin(2 * np.pi * t / 365)             # Annual seasonality
            noise    = np.random.normal(0, 0.02 * base, n_per_group)
            emission = np.clip(trend + seasonal + noise, 0.001, None)
            
            records = pd.DataFrame({
                'date':            dates.strftime('%Y-%m-%d'),
                'emission_date':   dates,
                'country':         country,
                'sector':          sector,
                'mtco2_per_day':   emission,
                'year':            dates.year,
                'month':           dates.month,
                'day_of_week':     dates.dayofweek,
                'day_of_year':     dates.dayofyear,
                'quarter':         dates.quarter,
                'is_weekend':      (dates.dayofweek >= 5).astype(int),
                'month_sin':       np.sin(2 * np.pi * dates.month / 12),
                'month_cos':       np.cos(2 * np.pi * dates.month / 12),
                'lag_1d':          pd.Series(emission).shift(1).values,
                'lag_7d':          pd.Series(emission).shift(7).values,
                'lag_30d':         pd.Series(emission).shift(30).values,
                'rolling_avg_7d':  pd.Series(emission).rolling(7, min_periods=1).mean().values,
                'rolling_avg_30d': pd.Series(emission).rolling(30, min_periods=1).mean().values,
            })
            all_records.append(records)
    
    df = pd.concat(all_records, ignore_index=True).dropna(subset=['lag_7d'])
    logger.info(f"Synthetic data: {len(df):,} records")
    return df


def save_all_metrics(all_metrics: list):
    """
    Combines all model metrics and saves in JSON and CSV formats.
    Creates the results table to be displayed on the dashboard.
    
    Args:
        all_metrics: List of metrics dictionaries for each model
    """
    metrics_path = MODELS_DIR / "all_model_metrics.json"
    csv_path     = MODELS_DIR / "all_model_metrics.csv"
    
    with open(metrics_path, 'w') as f:
        json.dump(all_metrics, f, indent=2)
    
    pd.DataFrame(all_metrics).to_csv(csv_path, index=False)
    
    logger.info(f"\nMetrics saved:")
    logger.info(f"  JSON: {metrics_path}")
    logger.info(f"  CSV:  {csv_path}")


def main():
    """
    Main training orchestrator.
    Trains all models sequentially and logs results to MLflow.
    """
    parser = argparse.ArgumentParser(description='Carbon Footprint ML Training')
    parser.add_argument('--skip-spark', action='store_true',
                        help='Skip Spark MLlib model')
    parser.add_argument('--skip-lstm', action='store_true',
                        help='Skip LSTM model')
    parser.add_argument('--country', default='CN',
                        help='Country for LSTM and XGBoost (default: CN)')
    parser.add_argument('--sector', default='Power',
                        help='Sector for LSTM (default: Power)')
    parser.add_argument('--model', default='all', choices=['all', 'xgboost_reg', 'xgboost_clf', 'lstm', 'spark_rf'],
                        help='Specific model to train (default: all)')
    args = parser.parse_args()
    
    logger.info("=" * 65)
    logger.info("Carbon Footprint Prediction — ML Training Process")
    logger.info(f"Start: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    logger.info("=" * 65)
    
    # Initialize MLflow
    setup_mlflow()
    
    # Import training logger
    try:
        from ml.training_logger import update_status
        update_status("Orchestrator", "running", message="ML Training process initiated. Loading dataset...")
    except Exception as e:
        logger.warning(f"Could not import/use training logger: {e}")
        update_status = None
        
    # Load data
    df = load_carbon_monitor_data()
    
    all_metrics = []
    start_time  = time.time()
    
    # =========================================================================
    # MODEL 1: XGBoost Regression
    # =========================================================================
    if args.model in ['all', 'xgboost_reg']:
        logger.info("\n[1/4] XGBoost Regression Model...")
        if update_status:
            update_status("XGBoost Regressor", "running", message="Training XGBoost Regression model...")
        
        try:
            from ml.xgboost_model import train_regression_model
            
            with mlflow.start_run(run_name="XGBoost_Regression"):
                xgb_reg_results = train_regression_model(df)
                
                if xgb_reg_results:
                    metrics = xgb_reg_results['metrics']
                    
                    # Log to MLflow
                    mlflow.log_metrics({
                        "mae":  metrics['mae'],
                        "rmse": metrics['rmse'],
                        "r2":   metrics['r2']
                    })
                    mlflow.log_params({
                        "model":          "XGBoost",
                        "task":           "regression",
                        "n_estimators":   500,
                        "learning_rate":  0.05
                    })
                    mlflow.xgboost.log_model(xgb_reg_results['model'], "model")
                    
                    all_metrics.append(metrics)
                    logger.info(f"✓ XGBoost Regression: MAE={metrics['mae']:.4f}, R²={metrics['r2']:.4f}")
                    if update_status:
                        update_status("XGBoost Regressor", "completed", message=f"XGBoost Regression completed. R² = {metrics['r2']:.4f}")
        except Exception as e:
            logger.error(f"XGBoost Regression error: {e}")
            if update_status:
                update_status("XGBoost Regressor", "failed", error=str(e))
    
    # =========================================================================
    # MODEL 2: XGBoost Classification
    # =========================================================================
    if args.model in ['all', 'xgboost_clf']:
        logger.info("\n[2/4] XGBoost Classification Model...")
        if update_status:
            update_status("XGBoost Classifier", "running", message="Training XGBoost Classification model...")
        
        try:
            from ml.xgboost_model import train_classification_model
            
            with mlflow.start_run(run_name="XGBoost_Classification"):
                xgb_clf_results = train_classification_model()
                
                if xgb_clf_results:
                    metrics = xgb_clf_results['metrics']
                    
                    mlflow.log_metrics({
                        "accuracy":  metrics['accuracy'],
                        "precision": metrics['precision'],
                        "recall":    metrics['recall'],
                        "f1":        metrics['f1']
                    })
                    mlflow.log_params({
                        "model": "XGBoost",
                        "task":  "classification",
                        "n_classes": 3
                    })
                    mlflow.xgboost.log_model(xgb_clf_results['model'], "model")
                    
                    all_metrics.append(metrics)
                    logger.info(f"✓ XGBoost Classification: Acc={metrics['accuracy']:.4f}, F1={metrics['f1']:.4f}")
                    if update_status:
                        update_status("XGBoost Classifier", "completed", message=f"XGBoost Classification completed. F1 = {metrics['f1']:.4f}")
        except Exception as e:
            logger.error(f"XGBoost Classification error: {e}")
            if update_status:
                update_status("XGBoost Classifier", "failed", error=str(e))
    
    # =========================================================================
    # MODEL 3: LSTM
    # =========================================================================
    if args.model in ['all', 'lstm'] and not args.skip_lstm:
        logger.info(f"\n[3/4] LSTM Model ({args.country}/{args.sector})...")
        
        try:
            from ml.lstm_model import train_lstm
            
            with mlflow.start_run(run_name=f"LSTM_{args.country}_{args.sector}"):
                lstm_results = train_lstm(
                    df,
                    country=args.country,
                    sector=args.sector,
                    epochs=50,
                    batch_size=32
                )
                
                if lstm_results:
                    metrics = lstm_results['metrics']
                    
                    mlflow.log_metrics({
                        "mae":  metrics['mae'],
                        "rmse": metrics['rmse'],
                        "r2":   metrics['r2']
                    })
                    mlflow.log_params({
                        "model":    "LSTM",
                        "country":  args.country,
                        "sector":   args.sector,
                        "seq_len":  30,
                        "horizon":  7,
                        "hidden":   128,
                        "layers":   2
                    })
                    
                    all_metrics.append(metrics)
                    logger.info(f"✓ LSTM: MAE={metrics['mae']:.4f}, R²={metrics['r2']:.4f}")
        except Exception as e:
            logger.error(f"LSTM error: {e}")
            if update_status:
                update_status("LSTM (PyTorch)", "failed", error=str(e))
    else:
        if args.skip_lstm:
            logger.info("\n[3/4] LSTM skipped (--skip-lstm flag)")
    
    # =========================================================================
    # MODEL 4: Spark MLlib Random Forest
    # =========================================================================
    if args.model in ['all', 'spark_rf'] and not args.skip_spark:
        logger.info("\n[4/4] Spark MLlib Random Forest...")
        if update_status:
            update_status("Spark MLlib RF", "running", message="Training Spark MLlib Random Forest...")
        
        try:
            from ml.spark_mllib_model import train_distributed_random_forest, create_spark_session
            
            spark = create_spark_session()
            
            with mlflow.start_run(run_name="SparkMLlib_RandomForest"):
                rf_results = train_distributed_random_forest(spark)
                
                if rf_results:
                    metrics = rf_results['metrics']
                    
                    mlflow.log_metrics({
                        "mae":  metrics['mae'],
                        "rmse": metrics['rmse'],
                        "r2":   metrics['r2']
                    })
                    mlflow.log_params({
                        "model":    "RandomForest",
                        "engine":   "SparkMLlib",
                        "numTrees": 100
                    })
                    
                    all_metrics.append(metrics)
                    logger.info(f"✓ Spark RF: MAE={metrics['mae']:.4f}, R²={metrics['r2']:.4f}")
                    if update_status:
                        update_status("Spark MLlib RF", "completed", message=f"Spark MLlib Random Forest completed. R² = {metrics['r2']:.4f}")
            
            spark.stop()
        except Exception as e:
            logger.error(f"Spark MLlib error: {e}")
            if update_status:
                update_status("Spark MLlib RF", "failed", error=str(e))
    else:
        if args.skip_spark:
            logger.info("\n[4/4] Spark MLlib skipped (--skip-spark flag)")
    
    # =========================================================================
    # FINAL REPORT
    # =========================================================================
    total_time = time.time() - start_time
    
    logger.info("\n" + "=" * 65)
    logger.info("MODEL COMPARISON TABLE")
    logger.info("=" * 65)
    
    if all_metrics:
        metrics_df = pd.DataFrame(all_metrics)
        print(metrics_df.to_string(index=False))
        
        # Save
        save_all_metrics(all_metrics)
    
    logger.info(f"\nTotal duration: {total_time:.1f} seconds ({total_time/60:.1f} minutes)")
    logger.info(f"MLflow UI: mlflow ui --backend-store-uri {MLFLOW_TRACKING}")
    logger.info(f"           → http://localhost:5000")
    logger.info("=" * 65)
    
    if update_status:
        update_status("Orchestrator", "completed", message=f"Training workflow completed in {total_time:.1f} seconds.")


if __name__ == "__main__":
    main()
